/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3VW5Aoz4t7z
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { CardContent, Card } from "@/components/ui/card";

export function MainPage() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-gray-100 dark:bg-gray-800 py-8 md:py-12 lg:py-16 relative">
        <div className="container flex flex-col items-center text-center gap-4 md:gap-6 lg:gap-8">
          <div className="space-y-2 flex flex-col items-center gap-4">
            <Avatar className="w-32 h-32 border">
              <AvatarImage alt="RR" src="/placeholder-avatar.jpg" />
              <AvatarFallback>RR</AvatarFallback>
            </Avatar>
            <div>
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
                John Doe
              </h1>
              <p className="text-lg text-gray-500 dark:text-gray-400 max-w-[600px] md:text-xl">
                Passionate full-stack developer with expertise in building
                modern, scalable web applications.
              </p>
            </div>
          </div>
          <div className="flex flex-col sm:flex-row items-center gap-3">
            <Button>View Projects</Button>
            <Button variant="secondary">Contact Me</Button>
            <Button
              className="absolute top-4 right-4 md:top-6 md:right-6 lg:top-8 lg:right-8"
              size="icon"
              variant="ghost"
            >
              <SunIcon className="w-5 h-5" />
              <span className="sr-only">Toggle dark mode</span>
            </Button>
          </div>
          <div className="flex gap-4">
            <Link
              className="text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-50"
              href="#"
            >
              <GithubIcon className="w-5 h-5" />
            </Link>
            <Link
              className="text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-50"
              href="#"
            >
              <LinkedinIcon className="w-5 h-5" />
            </Link>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container px-4 md:px-6 lg:px-8">
            <div className="space-y-6 md:space-y-8 lg:space-y-10">
              <div className="text-center">
                <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">
                  Featured Projects
                </h2>
                <p className="text-gray-500 dark:text-gray-400 max-w-[600px] mx-auto mt-2 md:text-lg">
                  Check out some of my recent web development projects.
                </p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8 lg:gap-10">
                <Card>
                  <img
                    alt="Project 1"
                    className="rounded-t-lg object-cover w-full h-48"
                    height={400}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "600/400",
                      objectFit: "cover",
                    }}
                    width={600}
                  />
                  <CardContent className="p-4 md:p-6">
                    <h3 className="text-lg font-bold mb-2">Project 1</h3>
                    <p className="text-gray-500 dark:text-gray-400 line-clamp-3">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      Sed euismod, nisl nec ultricies lacinia, nisl nisl aliquam
                      nisl, eget aliquam nisl nisl sit amet nisl.
                    </p>
                  </CardContent>
                </Card>
                <Card>
                  <img
                    alt="Project 2"
                    className="rounded-t-lg object-cover w-full h-48"
                    height={400}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "600/400",
                      objectFit: "cover",
                    }}
                    width={600}
                  />
                  <CardContent className="p-4 md:p-6">
                    <h3 className="text-lg font-bold mb-2">Project 2</h3>
                    <p className="text-gray-500 dark:text-gray-400 line-clamp-3">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      Sed euismod, nisl nec ultricies lacinia, nisl nisl aliquam
                      nisl, eget aliquam nisl nisl sit amet nisl.
                    </p>
                  </CardContent>
                </Card>
                <Card>
                  <img
                    alt="Project 3"
                    className="rounded-t-lg object-cover w-full h-48"
                    height={400}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "600/400",
                      objectFit: "cover",
                    }}
                    width={600}
                  />
                  <CardContent className="p-4 md:p-6">
                    <h3 className="text-lg font-bold mb-2">Project 3</h3>
                    <p className="text-gray-500 dark:text-gray-400 line-clamp-3">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      Sed euismod, nisl nec ultricies lacinia, nisl nisl aliquam
                      nisl, eget aliquam nisl nisl sit amet nisl.
                    </p>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 dark:bg-gray-800 py-12 md:py-16 lg:py-20">
          <div className="container px-4 md:px-6 lg:px-8">
            <div className="space-y-6 md:space-y-8 lg:space-y-10">
              <div className="text-center">
                <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">
                  Skills
                </h2>
                <p className="text-gray-500 dark:text-gray-400 max-w-[600px] mx-auto mt-2 md:text-lg">
                  Here are some of the technologies I\'m proficient in.
                </p>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 md:gap-6 lg:gap-8">
                <div className="flex flex-col items-center gap-2">
                  <RedoDotIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">React</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <ForwardIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Next.js</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <TypeIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">TypeScript</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <WindIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Tailwind CSS</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <BellIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Vercel</span>
                </div>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 md:gap-6 lg:gap-8">
                <div className="flex flex-col items-center gap-2">
                  <LeafIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Node.js</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <PianoIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Prisma</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <SignpostIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">PostgreSQL</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <DatabaseIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">MongoDB</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <GitGraphIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Git</span>
                </div>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 md:gap-6 lg:gap-8">
                <div className="flex flex-col items-center gap-2">
                  <BellIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Vercel</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <ContainerIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Docker</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <CloudIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Kubernetes</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <CloudIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">AWS</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <GlobeIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">GCP</span>
                </div>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 md:gap-6 lg:gap-8">
                <div className="flex flex-col items-center gap-2">
                  <PyramidIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Python</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <EclipseIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Java</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <CpuIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">C#</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <WrenchIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Rust</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <GoalIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Go</span>
                </div>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 md:gap-6 lg:gap-8">
                <div className="flex flex-col items-center gap-2">
                  <TriangleIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">TensorFlow</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <PyramidIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">PyTorch</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <ScissorsIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Scikit-learn</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <PyramidIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Keras</span>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <RabbitIcon className="w-8 h-8" />
                  <span className="text-sm font-medium">Pandas</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 dark:bg-gray-950 py-6 md:py-8 lg:py-10">
        <div className="container flex flex-col items-center gap-4 md:flex-row md:justify-between px-4 md:px-6 lg:px-8">
          <p className="text-sm text-gray-400 dark:text-gray-500">
            © 2024 John Doe. All rights reserved.
          </p>
          <div className="flex gap-4">
            <Link
              className="text-gray-400 dark:text-gray-500 hover:text-gray-50 dark:hover:text-gray-50"
              href="#"
            >
              <GithubIcon className="w-5 h-5" />
            </Link>
            <Link
              className="text-gray-400 dark:text-gray-500 hover:text-gray-50 dark:hover:text-gray-50"
              href="#"
            >
              <LinkedinIcon className="w-5 h-5" />
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 1 12 0c0 7 3 9 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 3.4" />
    </svg>
  );
}

function CloudIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 6.71-9h1.79a4.5 4.5 9Z" />
    </svg>
  );
}

function ContainerIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 7.7c0-.6-.4-1.2-.8-1.5l-6.3-3.9a1.72 1.72 0 0-1.7 0l-10.3 6c-.5.2-.9.8-.9 1.4v6.6c0 .5.4 1.2.8 1.5l6.3 3.9a1.72 1.7 0l10.3-6c.5-.3.9-1 .9-1.5Z" />
      <path d="M10 21.9V14L2.1 9.1" />
      <path d="m10 14 11.9-6.9" />
      <path d="M14 19.8v-8.1" />
      <path d="M18 17.5V9.4" />
    </svg>
  );
}

function CpuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="16" x="4" y="4" rx="2" />
      <rect width="6" height="6" x="9" y="9" rx="1" />
      <path d="M15 2v2" />
      <path d="M15 20v2" />
      <path d="M2 15h2" />
      <path d="M2 9h2" />
      <path d="M20 15h2" />
      <path d="M20 9h2" />
      <path d="M9 2v2" />
      <path d="M9 20v2" />
    </svg>
  );
}

function DatabaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 21 19V5" />
      <path d="M3 12A9 3 0 21 12" />
    </svg>
  );
}

function EclipseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a7 7 0 1 10" />
    </svg>
  );
}

function ForwardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="15 17 20 12 7" />
      <path d="M4 18v-2a4 4 0 1 4-4h12" />
    </svg>
  );
}

function GitGraphIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="5" cy="6" r="3" />
      <path d="M5 9v6" />
      <circle cx="5" cy="18" r="3" />
      <path d="M12 3v18" />
      <circle cx="19" cy="6" r="3" />
      <path d="M16 15.7A9 9 0 19" />
    </svg>
  );
}

function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0-1-3.5c3 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2c-.3 1.15-.3 2.35 3.5A5.403 5.403 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

function GlobeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 20 0-20" />
      <path d="M2 12h20" />
    </svg>
  );
}

function GoalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 13V2l8 4-8 4" />
      <path d="M20.561 10.222a9 9 0 1 1-12.55-5.29" />
      <path d="M8.002 9.997a5 5 0 1 8.9 2.02" />
    </svg>
  );
}

function LeafIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 20A7 7 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 4.18 8 5.5-4.78 10-10 10Z" />
      <path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13" />
    </svg>
  );
}

function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 1 6v7h-4v-7a2 2 0-2-2 0-2 2v7h-4v-7a6 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function PianoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18.5 8c-1.4 0-2.6-.8-3.2-2A6.87 6.87 0 2 9v11a2 2h16a2 2-2v-8.5C22 9.6 20.4 8 18.5" />
      <path d="M2 14h20" />
      <path d="M6 14v4" />
      <path d="M10 14v4" />
      <path d="M14 14v4" />
      <path d="M18 14v4" />
    </svg>
  );
}

function PyramidIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 16.88a1 1 0 1-.32-1.43l9-13.02a1 1.64 0l9 13.01a1 1-.32 1.44l-8.51 4.86a2 2 1-1.98 0Z" />
      <path d="M12 2v20" />
    </svg>
  );
}

function RabbitIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M13 16a3 3 0 1 2.24 5" />
      <path d="M18 12h.01" />
      <path d="M18 21h-8a4 4 0 1-4-4 7 1 7-7h.2L9.6 6.4a1 2.8-2.8L15.8 7h.2c3.3 6 2.7 6v1a2 2 1-2 2h-1a3 3 0-3" />
      <path d="M20 8.54V4a2 2 0 1 0-4 0v3" />
      <path d="M7.612 12.524a3 3 0 1 0-1.6 4.3" />
    </svg>
  );
}

function RedoDotIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="17" r="1" />
      <path d="M21 7v6h-6" />
      <path d="M3 17a9 9 0 1 9-9 6 2.3l3 2.7" />
    </svg>
  );
}

function ScissorsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="6" cy="6" r="3" />
      <path d="M8.12 8.12 12" />
      <path d="M20 4 8.12 15.88" />
      <circle cx="6" cy="18" r="3" />
      <path d="M14.8 14.8 20" />
    </svg>
  );
}

function SignpostIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3v3" />
      <path d="M18.5 13h-13L2 9.5 5.5 6h13L22 9.5Z" />
      <path d="M12 13v8" />
    </svg>
  );
}

function SunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41" />
      <path d="m17.66 17.66 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  );
}

function TriangleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M13.73 4a2 2 0 0-3.46 0l-8 14A2 4 21h16a2 1.73-3Z" />
    </svg>
  );
}

function TypeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="4 7 20" />
      <line x1="9" x2="15" y1="20" y2="20" />
      <line x1="12" x2="12" y1="4" y2="20" />
    </svg>
  );
}

function WindIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.7 7.7a2.5 2.5 0 1 1.8 4.3H2" />
      <path d="M9.6 4.6A2 2 0 1 11 8H2" />
      <path d="M12.6 19.4A2 2 0 1 14 16H2" />
    </svg>
  );
}

function WrenchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.7 6.3a1 1 0 1.4l1.6 1.6a1 1.4 0l3.77-3.77a6 6 1-7.94 7.94l-6.91 6.91a2.12 2.12 1-3-3l6.91-6.91a6 7.94-7.94l-3.76 3.76z" />
    </svg>
  );
}
